### PR TITLE
Produce jakarta artifacts

### PR DESCRIPTION
**Pull request by beikov**

### CODE REVIEW

**Comment by chengfang** [comment]
@beikov can you create a JIRA for this (https://issues.redhat.com/issues/?jql=project%20%3D%20WFTC%20ORDER%20BY%20key%20DESC)? Given the scope of this pull request, it will be good to have more details such as motivation, overall approach for producing Jakarta artifacts, impact on current artifacts, application code, and consuming projects (e.g., WildFly), and any other related JIRA.

**Comment by beikov** [comment]
Hi @chengfang I created https://issues.redhat.com/browse/WFTC-92 for this. Please let me know if you need anything else to get this done?

**Comment by chengfang** [comment]
@beikov  sorry for the delay. I checked the jakarta variant jar, its META-INF/INDEX.LIST and META-INF/MANIFEST.MF are the same as the javaee variant jar. Since the jakarta artifact has its own GAV, should it identify itself as such in its INDEX.LIST and MANIFEST?

The current content of jakarta jar MANIFEST:
```
Manifest-Version: 1.0
Implementation-Title: WildFly transaction client
Implementation-Version: 1.2.0.Final-SNAPSHOT
Java-Version: 1.8.0_261
Built-By: cfang
Scm-Connection: scm:git:git@github.com:jboss/jboss-parent-pom.git/wild
 fly-transaction-client-parent/wildfly-transaction-client
Specification-Vendor: JBoss by Red Hat
Os-Arch: x86_64
Specification-Title: WildFly transaction client
Implementation-Vendor-Id: org.wildfly.transaction
Java-Vendor: Oracle Corporation
Os-Name: Mac OS X
Scm-Url: http://github.com/jboss/jboss-parent-pom/wildfly-transaction-
 client-parent/wildfly-transaction-client
Implementation-Vendor: JBoss by Red Hat
Os-Version: 10.15.7
Scm-Revision: 499f150bae7938c6f53e7a083bdb16c0f1dc4e4c
Created-By: Apache Maven 3.6.3
Build-Jdk: 1.8.0_261
Specification-Version: 1.2
Implementation-URL: http://www.jboss.org/wildfly-transaction-client-pa
 rent/wildfly-transaction-client
```

**Comment by beikov** [comment]
Hi @chengfang, I don't have any preference, but at least for Hibernate we don't change these files. Is there anything specific that you would like to change?

**Comment by chengfang** [comment]
My concern is that other tools and framework may be confused between the 2 variants. But right now it doesn't seem to be a big problem.

**Review by chengfang — APPROVED** [review]

**Pull request merged**
