### PR TITLE
[WFLY-11357] add priv block to FileSystemXAResourceRegistry

### PR DESCRIPTION
**Pull request by baranowb**
Issues: https://issues.jboss.org/browse/WFLY-11357 ,  https://issues.jboss.org/browse/WFTC-53 
PR master: https://github.com/wildfly/wildfly-transaction-client/pull/61

### CODE REVIEW

**Comment by jamezp** [comment]
This should use the https://issues.jboss.org/browse/WFTC-53 JIRA.

**Comment by baranowb** [comment]
WDYM? mkdir and open require r/w permission.
mkdir(): https://docs.oracle.com/javase/7/docs/api/java/io/File.html#mkdir()
FIleChannel.open(): https://docs.oracle.com/javase/7/docs/api/java/nio/channels/FileChannel.html#open(java.nio.file.Path,%20java.nio.file.OpenOption...)

**Comment by dmlloyd** [comment]
Yes of course, but any time you add doPrivileged somewhere, you must also add a corresponding permission check to prevent malicious code from subverting it.

See http://word-bits.flurg.com/presentations/security-manager/index.html#/11 for more info.

**Comment by baranowb** [comment]
You mean to proof it in case JDK classes were tampered with?

**Pull request merged**
