### PR TITLE
Fix: Subordinate XA calls to do not use the matching EJB authentication or ssl context

### PR DESCRIPTION
**Pull request by chrisruffalo**
This is a partial fix to the issue outlined here https://github.com/chrisruffalo/three-tier-issue

The result of this PR is that the subordinate calls succeed instead of throwing exceptions however periodic recovery still fails with exceptions similar to the following despite seemingly using the same rules/match.

```
12:03:01,316 WARN  [com.arjuna.ats.jta] (Periodic Recovery) ARJUNA016027: Local XARecoveryModule.xaRecovery got XA exception ARJUNA016099: Unknown error code:0: javax.transaction.xa.XAException: WFHTTP000005: Invalid response code 404 (full response ClientResponse{responseHeaders={content-length=[74], content-type=[text/html], date=[Wed, 24 Feb 2021 17:03:01 GMT]}, responseCode=404, status='', protocol=HTTP/2.0})
	at org.wildfly.httpclient.transaction.HttpRemoteTransactionPeer.recover(HttpRemoteTransactionPeer.java:125)
	at org.wildfly.transaction.client.SubordinateXAResource.recover(SubordinateXAResource.java:241)
	at org.wildfly.transaction.client.SubordinateXAResource.recover(SubordinateXAResource.java:237)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.xaRecoveryFirstPass(XARecoveryModule.java:659)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:240)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkFirstPass(XARecoveryModule.java:182)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:770)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:382)
Caused by: java.io.IOException: WFHTTP000005: Invalid response code 404 (full response ClientResponse{responseHeaders={content-length=[74], content-type=[text/html], date=[Wed, 24 Feb 2021 17:03:01 GMT]}, responseCode=404, status='', protocol=HTTP/2.0})
	at org.wildfly.httpclient.common.HttpTargetContext$1$1.lambda$completed$4(HttpTargetContext.java:236)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
	at java.lang.Thread.run(Thread.java:748)
```

### CODE REVIEW

**Comment by chrisruffalo** [comment]
Once this fix is approved I would like to backport it into the 1.13 branch

**Comment by chrisruffalo** [comment]
Also the recovery exception is related to https://issues.redhat.com/browse/WFLY-13696 and is not related to the functionality here. Deleting the contents of `standalone/data/ejb-xa-recovery` before starting the three-tier example provided removes the periodic recovery error messages.

**Comment by gaol** [comment]
@chrisruffalo I created https://issues.redhat.com/browse/WFTC-89 to tack the issue, and back port your PR to #111 , would you please update this PR's description to link to the Jira? thanks :)

**Review by tadamski — COMMENTED** [review]
superseded by https://github.com/wildfly/wildfly-http-client/pull/57

**Pull request closed without merging**
