### PR TITLE
[WFTC-81] always use RemoteUserTransaction for txn:UserTransaction

### PR DESCRIPTION
**Pull request by istudens**
https://issues.redhat.com/browse/WFTC-81

### CODE REVIEW

**Comment by istudens** [comment]
@tadamski @dmlloyd could you review please? thanks

**Comment by tadamski** [comment]
@istudens could you please create PR with this fix to master as well?

**Comment by istudens** [comment]
@tadamski done #102

**Comment by tadamski** [comment]
thanks

**Pull request merged**
